### ISSUE TITLE
Holding laser interactor button during scene transition breaks laser interactor

### ISSUE THREAD

**Issue by TCFjord** [Fjordnet/UnityLIB-XRInteraction#4]
If you use a laser interactor to click and hold on a target object, then unload the scene containing that target object, the laser interactor will no longer be responsive and will pass through everything.

**Comment by fjordchrism** [comment]
Passing to @rygo6. This will also cause a Unity UI laser line renderer to stop responding if holding down during a scene transition (with DontDestroyOnLoad applied to StandardUserRoot).

**Comment by rygo6** [comment]
This is technically because the event system was getting destroyed in the scene that was unloading. Chris and me added in a condition to correct this. But the ideal solution is to never destroy your eventsystem.

Section of documentation should be added describing ideal VR scene layout. Something like having a 'Main' scene which contains the UserRoot, EventSystem, and other things should not be destroyed, then additively loading content in over the top.

New issue created to discuss this. #9
